import { NotificationPreferences } from "@/components/admin/NotificationPreferences";

const configured = Boolean(process.env.BREVO_API_KEY && process.env.BREVO_SENDER_EMAIL) || Boolean(process.env.SMTP_USER && process.env.SMTP_PASSWORD);

export function NotificationSettings() {
  return <section id="notifications" className="mt-8 a2e-card p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-black uppercase tracking-[.16em] text-champagne">Menu notifications</p><h2 className="mt-2 text-2xl font-black text-navy">Alertes leads, PDF et equipe</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ink/65">Choisissez le fournisseur, ajoutez plusieurs destinataires et activez les evenements utiles. Les adresses sont conservees en base ; les cles et mots de passe restent dans Portainer.</p></div><span className={`rounded-card px-3 py-2 text-sm font-black ${configured ? "bg-green-100 text-green-800" : "bg-pearl text-ink/65"}`}>{configured ? "Canal technique configure" : "Configuration a terminer"}</span></div>
    <NotificationPreferences />
    <div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-card border border-champagne/35 bg-pearl p-5"><h3 className="font-black text-navy">Brevo API recommande</h3><p className="mt-2 text-sm leading-6 text-ink/65">Pas de port SMTP a ouvrir, bonne delivrabilite et suivi des envois depuis Brevo.</p><dl className="mt-4 space-y-2 text-sm"><SettingRow name="BREVO_API_KEY" state={Boolean(process.env.BREVO_API_KEY)} secret /><SettingRow name="BREVO_SENDER_EMAIL" state={Boolean(process.env.BREVO_SENDER_EMAIL)} /></dl></div><div className="rounded-card border border-ink/10 bg-white p-5"><h3 className="font-black text-navy">OVH, Gmail ou autre SMTP</h3><p className="mt-2 text-sm leading-6 text-ink/65">OVH : ssl0.ovh.net:465. Gmail : smtp.gmail.com:465 avec un mot de passe d'application. Autre fournisseur : renseignez son hote SMTP dans Portainer.</p><dl className="mt-4 space-y-2 text-sm"><SettingRow name="SMTP_USER" state={Boolean(process.env.SMTP_USER)} /><SettingRow name="SMTP_PASSWORD" state={Boolean(process.env.SMTP_PASSWORD)} secret /></dl></div></div>
    <details className="mt-5 rounded-card border border-ink/10 bg-white p-5"><summary className="cursor-pointer font-black text-navy">Tutoriel de configuration</summary><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm leading-6 text-ink/70"><li>Choisissez Brevo, OVH, Gmail ou Autre SMTP ci-dessus.</li><li>Ajoutez les destinataires dans le champ prévu, un par ligne.</li><li>Dans Portainer, ouvrez la stack A2E puis les variables d'environnement. Ne mettez jamais ces secrets dans GitHub.</li><li>Redéployez la stack après ajout ou modification des variables.</li></ol><pre className="mt-4 overflow-x-auto rounded-card bg-navy p-4 text-xs leading-6 text-white">{`# Brevo API\nBREVO_API_KEY=...\nBREVO_SENDER_EMAIL=contact@ags-a2e.com\nBREVO_SENDER_NAME=A2E Renovation\n\n# OVH / Gmail / SMTP\nSMTP_HOST=ssl0.ovh.net\nSMTP_PORT=465\nSMTP_SECURE=true\nSMTP_USER=contact@ags-a2e.com\nSMTP_PASSWORD=...`}</pre><div className="mt-4 flex flex-wrap gap-4 text-sm font-black"><a className="text-navy underline" href="https://app.brevo.com/settings/keys/api" target="_blank" rel="noreferrer">Ouvrir les cles API Brevo</a><a className="text-navy underline" href="https://help.ovhcloud.com/csm/fr-mx-plan-configuration-d-un-logiciel-de-messagerie?id=kb_article_view&sysparm_article=KB0052042" target="_blank" rel="noreferrer">Documentation OVH</a></div></details>
  </section>;
}
function SettingRow({ name, state, secret = false }: { name: string; state: boolean; secret?: boolean }) { return <div className="flex items-center justify-between gap-3"><dt className="font-mono text-xs text-ink/70">{name}</dt><dd className={`text-xs font-black ${state ? "text-green-700" : "text-ink/45"}`}>{state ? (secret ? "Renseignee" : "Active") : "Manquante"}</dd></div>; }
