"use client";

import { useEffect, useState } from "react";

type Provider = "brevo" | "smtp" | "ovh" | "gmail";
type Settings = { provider: Provider; leadEmail: string; recipients: string[]; events: { leadCreated: boolean; pdfGenerated: boolean; mediaUploaded: boolean; securityAlert: boolean }; telegramEnabled: boolean; trackingEnabled: boolean; signatureDiscountPercent: number; signatureWindowDays: number; phone: string; instagram: string; facebook: string; linkedin: string };
const defaults: Settings = { provider: "brevo", leadEmail: "", recipients: [], events: { leadCreated: false, pdfGenerated: true, mediaUploaded: false, securityAlert: true }, telegramEnabled: false, trackingEnabled: true, signatureDiscountPercent: 5, signatureWindowDays: 15, phone: "", instagram: "", facebook: "", linkedin: "" };

export function NotificationPreferences() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [status, setStatus] = useState("Chargement...");
  const [config, setConfig] = useState({ brevoConfigured: false, smtpConfigured: false, telegramConfigured: false });
  useEffect(() => { fetch(`/api/admin/settings?ts=${Date.now()}`, { cache: "no-store" }).then((response) => response.json()).then((data) => { setSettings({ ...defaults, ...data.settings, events: { ...defaults.events, ...data.settings?.events }, recipients: data.settings?.recipients ?? [], ...data.contact }); setConfig(data); setStatus(""); }).catch(() => setStatus("Configuration indisponible")); }, []);
  if (!settings) return <p className="mt-4 text-sm text-ink/60">{status}</p>;
  const update = (patch: Partial<Settings>) => setSettings((old) => old ? { ...old, ...patch } : old);
  const updateEvent = (key: keyof Settings["events"], value: boolean) => update({ events: { ...settings.events, [key]: value } });
  async function save() { setStatus("Enregistrement..."); const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); setStatus(response.ok ? "Enregistre dans la base" : "Erreur d'enregistrement"); }
  return <div className="mt-6 rounded-card border border-ink/10 bg-white p-5">
    <div className="grid gap-4 md:grid-cols-2">
      <label className="grid gap-2 text-sm font-bold text-ink/80">Canal d'envoi<select className="input" value={settings.provider} onChange={(event) => update({ provider: event.target.value as Provider })}><option value="brevo">Brevo API (recommande)</option><option value="ovh">OVH SMTP</option><option value="gmail">Gmail SMTP</option><option value="smtp">Autre serveur SMTP</option></select></label>
      <label className="grid gap-2 text-sm font-bold text-ink/80">Destinataires des alertes<textarea className="input min-h-24" value={settings.recipients.join("\n")} onChange={(event) => update({ recipients: event.target.value.split(/[;,\n]/).map((item) => item.trim()).filter(Boolean) })} placeholder="julien@entreprise.fr\ncommercial@entreprise.fr" /><span className="text-xs font-normal text-ink/55">Un email par ligne. Les mots de passe ne sont jamais stockés ici.</span></label>
      <label className="grid gap-2 text-sm font-bold text-ink/80">Email historique<input className="input" type="email" value={settings.leadEmail} onChange={(event) => update({ leadEmail: event.target.value })} /></label>
      <div className="rounded-card border border-champagne/30 bg-pearl p-4 text-sm"><strong className="text-navy">Etat technique</strong><p className="mt-2">Brevo : {config.brevoConfigured ? "configure" : "a renseigner dans Portainer"}. SMTP : {config.smtpConfigured ? "configure" : "a renseigner dans Portainer"}.</p></div>
      <label className="grid gap-2 text-sm font-bold text-ink/80">Telephone public<input className="input" type="tel" value={settings.phone} onChange={(event) => update({ phone: event.target.value })} /></label>
      <label className="grid gap-2 text-sm font-bold text-ink/80">Instagram<input className="input" type="url" placeholder="https://instagram.com/..." value={settings.instagram} onChange={(event) => update({ instagram: event.target.value })} /></label>
      <label className="grid gap-2 text-sm font-bold text-ink/80">Facebook<input className="input" type="url" placeholder="https://facebook.com/..." value={settings.facebook} onChange={(event) => update({ facebook: event.target.value })} /></label>
      <label className="grid gap-2 text-sm font-bold text-ink/80">LinkedIn<input className="input" type="url" placeholder="https://linkedin.com/company/..." value={settings.linkedin} onChange={(event) => update({ linkedin: event.target.value })} /></label>
    </div>
    <div className="mt-6 border-t border-ink/10 pt-5"><h3 className="font-black text-navy">Evenements a notifier</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Check label="Nouveau lead soumis" checked={settings.events.leadCreated} onChange={(value) => updateEvent("leadCreated", value)} /><Check label="PDF genere ou telecharge" checked={settings.events.pdfGenerated} onChange={(value) => updateEvent("pdfGenerated", value)} /><Check label="Nouveau media publie" checked={settings.events.mediaUploaded} onChange={(value) => updateEvent("mediaUploaded", value)} /><Check label="Alerte securite / maintenance" checked={settings.events.securityAlert} onChange={(value) => updateEvent("securityAlert", value)} /><Check label="Alertes Telegram" checked={settings.telegramEnabled} onChange={(value) => update({ telegramEnabled: value })} /><Check label="Suivi des visites et clics" checked={settings.trackingEnabled} onChange={(value) => update({ trackingEnabled: value })} /></div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-ink/80">Avantage signature (%)<input className="input" type="number" min="0" max="15" value={settings.signatureDiscountPercent} onChange={(event) => update({ signatureDiscountPercent: Number(event.target.value) })} /></label><label className="grid gap-2 text-sm font-bold text-ink/80">Duree de validite (jours)<input className="input" type="number" min="1" max="60" value={settings.signatureWindowDays} onChange={(event) => update({ signatureWindowDays: Number(event.target.value) })} /></label></div>
    <div className="mt-5 flex items-center gap-3"><button type="button" onClick={save} className="min-h-11 rounded-card bg-navy px-5 font-black text-white">Enregistrer les notifications</button><span className="text-sm font-bold text-champagne">{status}</span></div>
  </div>;
}
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /> {label}</label>; }
