"use client";

import { useEffect, useState } from "react";

type Settings = { provider: "brevo" | "ovh"; leadEmail: string; telegramEnabled: boolean; trackingEnabled: boolean; signatureDiscountPercent: number; signatureWindowDays: number; phone: string; instagram: string; facebook: string; linkedin: string };

export function NotificationPreferences() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [status, setStatus] = useState("Chargement...");
  useEffect(() => { fetch("/api/admin/settings").then((response) => response.json()).then((data) => { setSettings({ ...data.settings, ...data.contact }); setStatus(""); }).catch(() => setStatus("Configuration indisponible")); }, []);
  if (!settings) return <p className="mt-4 text-sm text-ink/60">{status}</p>;
  const update = (patch: Partial<Settings>) => setSettings((old) => old ? { ...old, ...patch } : old);
  async function save() { setStatus("Enregistrement..."); const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); setStatus(response.ok ? "Enregistre" : "Erreur d'enregistrement"); }
  return <div className="mt-6 rounded-card border border-ink/10 bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-ink/80">Canal<select className="input" value={settings.provider} onChange={(event) => update({ provider: event.target.value as Settings["provider"] })}><option value="brevo">Brevo API</option><option value="ovh">OVH SMTP (a connecter)</option></select></label><label className="grid gap-2 text-sm font-bold text-ink/80">Email de notification<input className="input" type="email" value={settings.leadEmail} onChange={(event) => update({ leadEmail: event.target.value })} /></label><label className="grid gap-2 text-sm font-bold text-ink/80">Téléphone public<input className="input" type="tel" value={settings.phone} onChange={(event) => update({ phone: event.target.value })} /></label><label className="grid gap-2 text-sm font-bold text-ink/80">Instagram (URL complète)<input className="input" type="url" placeholder="https://instagram.com/..." value={settings.instagram} onChange={(event) => update({ instagram: event.target.value })} /></label><label className="grid gap-2 text-sm font-bold text-ink/80">Facebook (URL complète)<input className="input" type="url" placeholder="https://facebook.com/..." value={settings.facebook} onChange={(event) => update({ facebook: event.target.value })} /></label><label className="grid gap-2 text-sm font-bold text-ink/80">LinkedIn (URL complète)<input className="input" type="url" placeholder="https://linkedin.com/company/..." value={settings.linkedin} onChange={(event) => update({ linkedin: event.target.value })} /></label><label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" checked={settings.telegramEnabled} onChange={(event) => update({ telegramEnabled: event.target.checked })} /> Activer les alertes Telegram</label><label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" checked={settings.trackingEnabled} onChange={(event) => update({ trackingEnabled: event.target.checked })} /> Activer le suivi des visites et clics</label><label className="grid gap-2 text-sm font-bold text-ink/80">Avantage signature (%)<input className="input" type="number" min="0" max="15" value={settings.signatureDiscountPercent} onChange={(event) => update({ signatureDiscountPercent: Number(event.target.value) })} /></label><label className="grid gap-2 text-sm font-bold text-ink/80">Duree de validite (jours)<input className="input" type="number" min="1" max="60" value={settings.signatureWindowDays} onChange={(event) => update({ signatureWindowDays: Number(event.target.value) })} /></label></div><div className="mt-5 flex items-center gap-3"><button type="button" onClick={save} className="min-h-11 rounded-card bg-navy px-5 font-black text-white">Enregistrer les preferences</button><span className="text-sm font-bold text-champagne">{status}</span></div></div>;
}
