"use client";

import { useEffect, useState, type ReactNode } from "react";

type Item = { id: string; title: string; city: string; type: string; description: string; duration: string; budget: string; tags: string[]; active: boolean };

export function RealisationEditor() {
  const [items, setItems] = useState<Item[]>([]);
  const [status, setStatus] = useState("Chargement des fiches...");
  useEffect(() => { fetch("/api/admin/realisations").then((response) => response.json()).then((data) => { setItems(data.realisations ?? []); setStatus(""); }).catch(() => setStatus("Fiches indisponibles")); }, []);
  function update(id: string, patch: Partial<Item>) { setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); }
  async function save(item: Item) { setStatus("Enregistrement..."); const response = await fetch("/api/admin/realisations", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(item) }); setStatus(response.ok ? `Fiche mise a jour : ${item.title}` : "Erreur d'enregistrement"); }
  return <section className="mt-8 a2e-card p-6"><div className="flex items-end justify-between gap-4"><div><p className="font-black uppercase tracking-[.16em] text-champagne">Fiches projets</p><h2 className="mt-2 text-2xl font-black text-navy">Modifier les realisations</h2><p className="mt-2 text-sm leading-6 text-ink/65">Ces informations alimentent les cartes publiques et l'association des photos/videos.</p></div><span className="text-sm font-bold text-champagne">{status}</span></div><div className="mt-6 grid gap-5">{items.map((item) => <article key={item.id} className="rounded-card border border-ink/10 bg-pearl p-5"><div className="grid gap-3 md:grid-cols-2"><Field label="Titre"><input className="input" value={item.title} onChange={(event) => update(item.id, { title: event.target.value })} /></Field><Field label="Ville / zone"><input className="input" value={item.city} onChange={(event) => update(item.id, { city: event.target.value })} /></Field><Field label="Type de travaux"><input className="input" value={item.type} onChange={(event) => update(item.id, { type: event.target.value })} /></Field><Field label="Duree"><input className="input" value={item.duration} onChange={(event) => update(item.id, { duration: event.target.value })} /></Field><Field label="Budget affiche"><input className="input" value={item.budget} onChange={(event) => update(item.id, { budget: event.target.value })} /></Field><Field label="Tags, separes par des virgules"><input className="input" value={item.tags.join(", ")} onChange={(event) => update(item.id, { tags: event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean) })} /></Field><Field label="Description"><textarea className="input min-h-24" value={item.description} onChange={(event) => update(item.id, { description: event.target.value })} /></Field><label className="flex min-h-12 items-center gap-3 self-end text-sm font-bold"><input type="checkbox" checked={item.active} onChange={(event) => update(item.id, { active: event.target.checked })} /> Visible sur le site</label></div><button type="button" onClick={() => save(item)} className="mt-4 min-h-11 rounded-card bg-navy px-5 font-black text-white">Enregistrer cette fiche</button></article>)}</div></section>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-bold text-ink/80">{label}{children}</label>; }
