"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Calculator } from "lucide-react";
import { estimateProject, type EstimateInput } from "@/lib/pricing/estimate-engine";
import type { ProjectType } from "@/lib/pricing/price-data";

export function QuickEstimate() {
  const [projectType, setProjectType] = useState<ProjectType>("windows");
  const [surface, setSurface] = useState(80);
  const [quantity, setQuantity] = useState(4);
  const input = useMemo<EstimateInput>(() => ({ projectType, projectTypes: [projectType], city: "Ile-de-France", surface, material: "pvc", finish: "standard", urgency: "normal", access: "simple", windowItems: [{ kind: "window", quantity, material: "pvc", width: 125, height: 135, opening: "french", installPack: "renovation", shutter: false }], electricalItems: [{ kind: "socket", quantity: Math.max(1, quantity) }], plumbingFixtures: [{ kind: "shower", quantity: Math.max(1, quantity) }], includePanel: true, energy: { energyType: "electricity", currentDpe: "unknown", insulation: "unknown", household: 2, solar: false } }), [projectType, quantity, surface]);
  const result = useMemo(() => estimateProject(input), [input]);
  const isWindow = projectType === "windows";
  return <div className="a2e-card overflow-hidden border-navy/10 bg-white shadow-premium"><div className="grid gap-6 p-5 md:grid-cols-[1.1fr_.9fr] md:p-7"><div><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-card bg-pearl text-champagne"><Calculator size={20} /></span><div><p className="text-xs font-black uppercase tracking-[.16em] text-champagne">Calculette express</p><h3 className="text-xl font-black text-navy">Un premier ordre de grandeur en 30 secondes</h3></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-ink/80">Poste principal<select value={projectType} onChange={(event) => setProjectType(event.target.value as ProjectType)} className="input"><option value="windows">Fenêtres et ouvrants</option><option value="insulation">Isolation / ITE</option><option value="electricity">Électricité</option><option value="plumbing">Plomberie</option><option value="hvac">PAC / chauffage</option><option value="global">Rénovation globale</option></select></label><label className="grid gap-2 text-sm font-bold text-ink/80">{isWindow ? "Nombre d'ouvrants" : "Surface concernée (m²)"}<input type="number" min="1" value={isWindow ? quantity : surface} onChange={(event) => isWindow ? setQuantity(Math.max(1, Number(event.target.value))) : setSurface(Math.max(1, Number(event.target.value)))} className="input" /></label></div><p className="mt-4 text-sm leading-6 text-ink/60">Estimation indicative, ajustée ensuite selon les dimensions, les matériaux, l'accès et la visite technique.</p></div><div className="rounded-card bg-navy p-5 text-white"><p className="text-xs font-black uppercase tracking-[.16em] text-champagne">Fourchette estimative</p><p className="mt-3 text-3xl font-black">{result.low.toLocaleString("fr-FR")} à {result.high.toLocaleString("fr-FR")} €</p><p className="mt-2 text-sm text-white/70">Point central : <strong className="text-white">{result.mid.toLocaleString("fr-FR")} €</strong></p><Link href="/simulateur" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-card bg-white px-4 text-sm font-black text-navy transition hover:bg-pearl">Affiner poste par poste <ArrowRight size={16} /></Link></div></div><div className="flex flex-wrap gap-x-6 gap-y-2 border-t border-ink/10 bg-pearl px-5 py-4 text-sm font-bold text-navy md:px-7"><span>Prix visible à chaque choix</span><span>Options ajoutables</span><span>PDF détaillé après qualification</span></div></div>;
}
